# Generated by Django 5.0.3 on 2024-04-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
